project:
  type: website
  output-dir: _site

website:
  title: "Sobotka"
  navbar:
    background: primary
    left:
      - href: garminpython.qmd
        text: Data Lab
      - href: blog.qmd
        text: Blog
