name: Quarto Publish

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code ophalen
        uses: actions/checkout@v3

      - name: Python installeren
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Bibliotheken installeren
        run: |
          pip install jupyter matplotlib pandas scipy scikit-learn folium

      - name: Quarto installeren
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render website
        run: quarto render

      - name: Website bouwen en publiceren
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
